"
I am raised when a context cannot find in its sender chain an assertion failure context, that is, a context that compared two value, an actual and an expected.
"
Class {
	#name : 'StDebuggeAssertionFailureContextNotFound',
	#superclass : 'Exception',
	#category : 'NewTools-Debugger-Model',
	#package : 'NewTools-Debugger',
	#tag : 'Model'
}
